accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accountapp.views import hello_world, AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = "accountapp"

urlpatterns = [
    path('hello_world/',hello_world, name='hello_world'),

    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'),
    path('logout/',LogoutView.as_view(), name='logout'),

    path('create/',AccountCreateView.as_view(), name='create'), # 클래스뷰는 뒤에 aS_view(를 붙여야한다.
    path('detail/<int:pk>',AccountDetailView.as_view(), name='detail'), # 클래스뷰는 뒤에 aS_view(를 붙여야한다.
    path('update/<int:pk>',AccountUpdateView.as_view(), name='update'), # 클래스뷰는 뒤에 aS_view(를 붙여야한다.
    path('delete/<int:pk>',AccountDeleteView.as_view(), name='delete'), # 클래스뷰는 뒤에 aS_view(를 붙여야한다.
]

articleapp/urls.py
from django.urls import path
from django.views.generic import TemplateView

urlpatterns = [
    path('list/', TemplateView.as_view(template_name='articleapp/list.html'), name='list')
]

pragmatic/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')), #accountapp안에 있는 url로 분기처리
    path('profiles/', include('profileapp.urls')), #profileapp안에 있는 url로 분기처리
    path('articles/', include('articleapp.urls')), #articleapp안에 있는 url로 분기처리
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)   # 설정을 해주어야 이미지가 보일수있게 처리가 가능하다

profileapp/urls.py
from django.urls import path

from profileapp.views import ProfileCreateView, ProfileUpdateView

app_name = 'profileapp'

urlpatterns = [
    path('create/', ProfileCreateView.as_view(), name='create'),
    path('update/<int:pk>', ProfileUpdateView.as_view(), name='update'),
]

accountapp/models.py
from django.db import models

# Create your models here.

class HelloWorld(models.Model):
    text = models.CharField(max_length=255, null=False) # null은 컬럼 디폴트 체크

articleapp/models.py
from django.db import models

# Create your models here.

profileapp/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE, related_name='profile')

    image = models.ImageField(upload_to='profile/',null=True)
    nickname = models.CharField(max_length=20, unique=True )
    message = models.CharField(max_length=100, null=True)

profileapp/forms.py
from django.forms import ModelForm

from profileapp.models import Profile


class ProfileCreationForm(ModelForm):
    class Meta:
        model = Profile
        fields = ['image','nickname','message']

accountapp/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseForbidden
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView

from accountapp.decorators import account_ownership_required
from accountapp.foms import AccountUpdateForm
from accountapp.models import HelloWorld

has_ownership = [account_ownership_required, login_required]

# Create your views here.

@login_required
def hello_world(request):

        if request.method == "POST":

            temp = request.POST.get('hello_world_input')

            new_hello_world = HelloWorld()
            new_hello_world.text = temp
            new_hello_world.save()

            return HttpResponseRedirect(reverse('accountapp:hello_world'))
        else:
            hello_world_list = HelloWorld.objects.all()
            return render(request,'accountapp/hello_world.html', context={'hello_world_list': hello_world_list}) #context는 데이터 꾸러미


class AccountCreateView(CreateView):
    model = User  # User는 장고에서 기본제공해주는 모델
    form_class = UserCreationForm # 패스워드 검증 폼 내장 클래스
    success_url = reverse_lazy('accountapp:hello_world')  #함수와 클래스의 불러오는 방식의 차이, rever_lazy는 클래스형에서 사용함
    template_name = 'accountapp/create.html'


class AccountDetailView(DetailView):
    model = User
    context_object_name = 'target_user'
    template_name = 'accountapp/detail.html'

@method_decorator(has_ownership, 'get')
@method_decorator(has_ownership, 'post')
class AccountUpdateView(UpdateView):
    model = User  # User는 장고에서 기본제공해주는 모델
    context_object_name = 'target_user'
    form_class = AccountUpdateForm # 패스워드 검증 폼 내장 클래스
    success_url = reverse_lazy('accountapp:hello_world')  #함수와 클래스의 불러오는 방식의 차이, rever_lazy는 클래스형에서 사용함
    template_name = 'accountapp/update.html'

@method_decorator(has_ownership, 'get')
@method_decorator(has_ownership, 'post')
class AccountDeleteView(DeleteView):
    model = User
    context_object_name = 'target_user'
    success_url = reverse_lazy('accountapp:login')
    template_name = 'accountapp/delete.html'

articleapp/views.py
from django.shortcuts import render

# Create your views here.

profileapp/views.py
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, UpdateView

from profileapp.decorators import profile_ownership_required
from profileapp.forms import ProfileCreationForm
from profileapp.models import Profile


# Create your views here.

class ProfileCreateView(CreateView):
    model = Profile
    context_object_name = 'target_profile'
    form_class = ProfileCreationForm
    template_name = 'profileapp/create.html'

    def form_valid(self, form):
        temp_profile = form.save(commit=False)
        temp_profile.user = self.request.user
        temp_profile.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('accountapp:detail', kwargs={'pk': self.object.user.pk})


@method_decorator(profile_ownership_required, 'get')
@method_decorator(profile_ownership_required, 'post')
class ProfileUpdateView(UpdateView):
    model = Profile
    context_object_name = 'target_profile'
    form_class = ProfileCreationForm
    template_name = 'profileapp/update.html'

    def get_success_url(self):
        return reverse('accountapp:detail', kwargs={'pk': self.object.user.pk})

accountapp/templates/accountapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content%}

<div style="text-align: center; max-width:500px; margin: 4rem auto">
    <div class="mb-4">
        <h4>SignUp</h4>
    </div>
    <form action="{% url 'accountapp:create' %}" method="post">
        {% csrf_token %}
        <!--{{ form }}-->
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
    </form>
</div>

{% endblock %}

accountapp/templates/accountapp/delete.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content%}

<div style="text-align: center; max-width:500px; margin: 4rem auto">
    <div class="mb-4">
        <h4>Quit</h4>
    </div>
    <form action="{% url 'accountapp:delete' pk=target_user.pk %}" method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger rounded-pill col-6 mt-3">
    </form>
</div>

{% endblock %}

accountapp/templates/accountapp/detail.html
{% extends 'base.html' %}

{% block content %}

<div>
    <div style="text-align: center; max-width: 500px; margin: 4rem auto;">

        {% if target_user.profile %}
        <img src="{{ target_user.profile.image.url }}" alt="" style="height: 12rem; width: 12rem; border-radius:20rem; margin-bottom: 2rem;">
        <h2 style="font-family:'Share-Bold';">
            {{ target_user.profile.nickname }}
            {% if target_user == user %}
            <a href="{% url 'profileapp:update' pk=target_user.profile.pk %}">
                edit
            </a>
            {% endif %}
        </h2>
        <h5 style="margin-bottom: 3rem;">
        </h5>
        {% else %}
        {% if target_user == user %}
        <a href="{% url 'profileapp:create'  %}">
            <h2 style="font-family:'Share-Bold';">
                Create Profile
            </h2>
        </a>
        {% else %}
        <h2>
            {{ target_user.profile.message }}
            닉네임 미설정
        </h2>
        {% endif %}
        {% endif %}

        {% if target_user == user %}
        <a href="{% url 'accountapp:update' pk=user.pk %}">
            <p>
                Change Info
            </p>
        </a>
        <a href="{% url 'accountapp:delete' pk=user.pk %}">
            <p>
                Quit
            </p>
        </a>
        {% endif %}
    </div>
</div>

{% endblock %}

accountapp/templates/accountapp/hello_world.html
{% extends 'base.html' %}

{% block content%}

    <div style="border-radius: 1rem; margin: 2rem; text-align: center;">
        <h1 style="font-family: 'lobster', cursive;">
            Hello World List!
        </h1>

        <form action="/account/hello_world/" method="post">
            <!--장고에서 post요청을 할때는 crsf토큰(장고에서 제공하는 보안)을 명시해주어야 한다.-->
            {% csrf_token %}
            <div>
                <input type="text" name="hello_world_input" value="">
            </div>
            <div>
                <input type="submit" class="btn btn-primary" value="POST">
            </div>
        </form>

        {% if hello_world_list %}
            {% for hello_world in  hello_world_list %}
            <h1>
                {{ hello_world.text }}
            </h1>
            {% endfor %}
        {% endif %}

    </div>

{% endblock %}

accountapp/templates/accountapp/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

  <div style="text-align: center; max-width:500px; margin: 4rem auto">
      <div>
        <h4>Login</h4>
      </div>
    <div>
        <form action="" method="post">
        {% csrf_token %}
        <!--{{ form }}-->
        {% bootstrap_form form %}
         <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
        </form>
    </div>
  </div>

{% endblock %}

accountapp/templates/accountapp/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content%}

<div style="text-align: center; max-width:500px; margin: 4rem auto">
    <div class="mb-4">
        <h4>Chnage Info</h4>
    </div>
    <form action="{% url 'accountapp:update' pk=target_user.pk %}" method="post">
        {% csrf_token %}
        <!--{{ form }}-->
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
    </form>
</div>

{% endblock %}

articleapp/templates/articleapp/list.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

    <style>
    .container div {
      width: 200px;
      background-color: antiquewhite;
      display: flex;
      justify-content: center;
      align-items: center;
      border-radius: 1rem;
    }

    .container img {
      width: 100%;
      border-radius: 1rem;
    }

    </style>



    <div class="container">

      <div class="item1">
          <img src="https://picsum.photos/id/237/200/300">
      </div>
      <div class="item2">
          <img src="https://picsum.photos/id/237/200/200">
      </div>
      <div class="item3">
          <img src="https://picsum.photos/id/237/200/250">
      </div>
      <div class="item4">
          <img src="https://picsum.photos/id/237/200/300">
      </div>
      <div class="item5">
          <img src="https://picsum.photos/id/237/200/210">
      </div>
      <div class="item6">
          <img src="https://picsum.photos/id/237/200/300">
      </div>
      <div class="item7">
          <img src="https://picsum.photos/id/237/200/300">
      </div>
      <div class="item8">
          <img src="https://picsum.photos/id/237/200/300">
      </div>
      <div class="item9">
          <img src="https://picsum.photos/id/237/200/300">
      </div>
      <div class="item10">
          <img src="https://picsum.photos/id/237/200/300">
      </div>
      <div class="item11">
          <img src="https://picsum.photos/id/237/200/300">
      </div>
      <div class="item12">
          <img src="https://picsum.photos/id/237/200/300">
      </div>
      <div class="item13">
          <img src="https://picsum.photos/id/237/200/300">
      </div>

    </div>

    <script src="{% static 'js/magicgrid.js' %}"></script>

{% endblock %}

profileapp/templates/profileapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content%}

<div style="text-align: center; max-width:500px; margin: 4rem auto">
    <div class="mb-4">
        <h4>Profile Create</h4>
    </div>
    <form action="{% url 'profileapp:create' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <!--{{ form }}-->
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
    </form>
</div>

{% endblock %}

profileapp/templates/profileapp/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content%}

<div style="text-align: center; max-width:500px; margin: 4rem auto">
    <div class="mb-4">
        <h4>Update Profile</h4>
    </div>
    <form action="{% url 'profileapp:update' pk=target_profile.pk %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <!--{{ form }}-->
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
    </form>
</div>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="ko">

{% include "head.html" %}

<body style="font-family:'Share-Bold';">

    {% include "header.html" %}

    <hr>

    {% block content %}
    {% endblock %}

    <hr>

    {% include "footer.html" %}

</body>
</html>

templates/footer.html
<div class="pragmatic_footer">
    <div class="pragmatic_footer_button">
        <span>공지사항</span> |
        <span>제휴문의</span> |
        <span>서비스 소개</span>
    </div>
    <div style="margin-top: 1rem;">
        <h6 class="pragmatic_logo">Pragmatic</h6>
    </div>
</div>

templates/head.html
{% load static %}

<head>
    <meta charset="UTF-8">
    <title>Pragmatic</title>

    <!-- BOOTSTRAP LINK -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

    <!--  GOOGLE FONTS LINK  -->
    <link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">

    <!-- DEFALT CSS LINK-->
    <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">

    <style>
        @font-face{
            font-family:'Share-Bold';
            src:local('Share-Bold'),
            url("{% static 'fonts/Share-Bold.ttf' %}") format("opentype");
        }
        @font-face{
            font-family:'Share-Italic';
            src:local('Share-Italic'),
            url("{% static 'fonts/Share-Italic.ttf' %}") format("opentype");
        }
        @font-face{
            font-family:'Share-BoldItalic';
            src:local('Share-BoldItalic'),
            url("{% static 'fonts/Share-BoldItalic.ttf' %}") format("opentype");
        }
        @font-face{
            font-family:'Share-Regular';
            src:local('Share-Regular'),
            url("{% static 'fonts/Share-Regular.ttf' %}") format("opentype");
        }
    </style>

</head>

templates/header.html
<div class="pragmatic_header">
    <div>
        <h1 style="pragmatic_logo">Pragmatic</h1>
    </div>
    <div>
        <span>nav1</span>
        <span>nav2</span>
        <span>nav3</span>
        {% if not user.is_authenticated %}
        <a href="{% url 'accountapp:login' %}?next={{ request.path }}">
            <span>login</span>
        </a>
        <a href="{% url 'accountapp:create' %}">
            <span>SignUp</span>
        </a>
        {% else %}
        <a href="{% url 'accountapp:detail' pk=user.pk %}">
            <span>MyPage</span>
        </a>
        <a href="{% url 'accountapp:logout' %}?next={{ request.path }}">
            <span>logout</span>
        </a>
        {% endif %}
    </div>
</div>